[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
restartPolicyType = "ON_FAILURE"
replicas = 1
startCommand = "bash start.sh"

[variables]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_railway"
DEBUG = "True"
RAILWAY_ENVIRONMENT = "production"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8080"

[build.env]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_minimal"
