[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements_ultra_minimal.txt"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
replicas = 1
startCommand = "gunicorn pagTickets.wsgi_no_django:application --bind 0.0.0.0:$PORT --workers 1 --timeout 30 --keep-alive 2"

[variables]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
DEBUG = "False"
RAILWAY_ENVIRONMENT = "production"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8080"

[build.env]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
