[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/ping/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
replicas = 1
startCommand = "gunicorn pagTickets.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 30 --max-requests 1000 --preload"

[variables]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
DEBUG = "False"
RAILWAY_ENVIRONMENT = "production"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8080"

[build.env]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
