[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements_ultra_minimal.txt"

[deploy]
healthcheckPath = "/ping/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
replicas = 1
startCommand = "python manage_ultra_simple.py migrate --noinput && gunicorn pagTickets.wsgi_ultra_simple:application --bind 0.0.0.0:$PORT --workers 1 --timeout 600"

[variables]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
DEBUG = "False"
RAILWAY_ENVIRONMENT = "production"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8080"

[build.env]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
