[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
healthcheckPath = "/ping/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
replicas = 1
startCommand = "python manage.py migrate --noinput && gunicorn pagTickets.wsgi:application --bind 0.0.0.0:$PORT --workers 1"

[variables]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
DEBUG = "False"
RAILWAY_ENVIRONMENT = "production"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8080"

[build.env]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
