[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x start_railway.sh && ./start_railway.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[experimental]
publicNetworkAccess = true
