[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
healthcheckPath = "/ready/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
replicas = 1
startCommand = "gunicorn pagTickets.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 1"

[variables]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
DEBUG = "False"
RAILWAY_ENVIRONMENT = "production"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8080"

[build.env]
DJANGO_SETTINGS_MODULE = "pagTickets.settings_ultra_simple"
