# Generated by Django 5.2.1 on 2025-07-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagTickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('grupo', models.CharField(default='ADMINISTRACION', max_length=100)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_exportada', models.BooleanField(default=False)),
                ('ruta_imagen_microsip', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='registroqr',
            name='exportado_microsip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='imagen_capturada',
            field=models.FileField(blank=True, null=True, upload_to='activos_imagenes/'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='mensaje_exportacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='activo_fijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagTickets.activofijo'),
        ),
    ]
