# Generated by Django 5.2.1 on 2025-07-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagTickets', '0002_activofijo_registroqr_exportado_microsip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroqr',
            name='activo_fijo',
        ),
        migrations.AlterModelOptions(
            name='registroqr',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Registro QR', 'verbose_name_plural': 'Registros QR'},
        ),
        migrations.RemoveField(
            model_name='registroqr',
            name='exportado_microsip',
        ),
        migrations.RemoveField(
            model_name='registroqr',
            name='imagen_capturada',
        ),
        migrations.RemoveField(
            model_name='registroqr',
            name='mensaje_exportacion',
        ),
        migrations.AddField(
            model_name='registroqr',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='registroqr',
            name='codigo',
            field=models.CharField(max_length=255, verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='registroqr',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.DeleteModel(
            name='ActivoFijo',
        ),
    ]
