# Generated by Django 5.2.1 on 2025-07-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagTickets', '0003_remove_registroqr_activo_fijo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código QR')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('no_serie', models.CharField(max_length=100, verbose_name='Número de Serie')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
