# Generated by Django 5.2.1 on 2025-07-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagTickets', '0004_activofijo'),
    ]

    operations = [
    ]
