# Generated by Django 5.2.1 on 2025-07-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagTickets', '0004_activofijo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivoFijo',
        ),
    ]
