# Generated by Django 5.2.1 on 2025-08-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagTickets', '0006_delete_activofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroqr',
            name='anos_vida_util',
            field=models.IntegerField(blank=True, null=True, verbose_name='Años Vida Útil'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='api_consultada',
            field=models.BooleanField(default=False, verbose_name='API Consultada'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='api_error',
            field=models.TextField(blank=True, verbose_name='Error de API'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='depreciacion_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depreciación Anual'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='especificaciones_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Especificaciones Técnicas'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='estado_activo',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('fuera_servicio', 'Fuera de Servicio')], default='bueno', max_length=20, verbose_name='Estado del Activo'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='fuentes_precio',
            field=models.TextField(blank=True, verbose_name='Fuentes de Precio'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Serie'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='precio_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Actual USD'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Compra USD'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='precio_max_mercado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Máx. Mercado'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='precio_min_mercado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Mín. Mercado'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='ultima_actualizacion_precio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización Precio'),
        ),
        migrations.AddField(
            model_name='registroqr',
            name='valor_depreciado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Depreciado'),
        ),
    ]
