# Generated by Django 5.2.1 on 2025-08-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrregistro',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de Código', 'verbose_name_plural': 'Registros de Códigos'},
        ),
        migrations.AddField(
            model_name='qrregistro',
            name='formato_barcode',
            field=models.CharField(blank=True, help_text='Formato del código de barras (CODE128, CODE39, EAN13, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qrregistro',
            name='marca_activo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrregistro',
            name='modelo_activo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrregistro',
            name='nombre_activo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qrregistro',
            name='tipo_codigo',
            field=models.CharField(choices=[('QR', 'Código QR'), ('BARCODE', 'Código de Barras')], default='QR', max_length=10),
        ),
    ]
